name: Update arXiv Papers Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-papers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd js && npm install node-fetch@2 jsdom  # Move to the `js` folder to install dependencies

    - name: Run fetchPapers script
      run: node js/fetchPapers.js  # Specify the path to fetchPapers.js